theme: jekyll-theme-modernist
title: <div dir="rtl"><a href="https://hondacy.github.io/hack-me"> <br><br> <img src="./img/encrypted.png"  width=100px alt="">בנק המשאלות</a>
description: <div dir="rtl"> הבנק שיכול להעביר לך 1,000 ש״ח!
display_header_text: true
google_analytics: G-WWZHB02T6V
languages: ["he", "en"]
default_locale: he
