theme: jekyll-theme-modernist
title: <div dir="rtl"> <br><br> <img src="img/encrypted.png"  width=100px alt="">בנק המשאלות!
description: <div dir="rtl"> הבנק שיכול להעביר לך 1,000 ש״ח!
display_header_text: true
